// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: ServiceLoyalty.proto

package sl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPersonalPromoCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdClient      int32  `protobuf:"varint,1,opt,name=idClient,proto3" json:"idClient,omitempty"`
	IdGroup       int32  `protobuf:"varint,2,opt,name=idGroup,proto3" json:"idGroup,omitempty"`
	NamePromoCode string `protobuf:"bytes,3,opt,name=namePromoCode,proto3" json:"namePromoCode,omitempty"`
}

func (x *AddPersonalPromoCodeRequest) Reset() {
	*x = AddPersonalPromoCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPersonalPromoCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPersonalPromoCodeRequest) ProtoMessage() {}

func (x *AddPersonalPromoCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPersonalPromoCodeRequest.ProtoReflect.Descriptor instead.
func (*AddPersonalPromoCodeRequest) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{0}
}

func (x *AddPersonalPromoCodeRequest) GetIdClient() int32 {
	if x != nil {
		return x.IdClient
	}
	return 0
}

func (x *AddPersonalPromoCodeRequest) GetIdGroup() int32 {
	if x != nil {
		return x.IdGroup
	}
	return 0
}

func (x *AddPersonalPromoCodeRequest) GetNamePromoCode() string {
	if x != nil {
		return x.NamePromoCode
	}
	return ""
}

type AddPersonalPromoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddPersonalPromoCodeResponse) Reset() {
	*x = AddPersonalPromoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPersonalPromoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPersonalPromoCodeResponse) ProtoMessage() {}

func (x *AddPersonalPromoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPersonalPromoCodeResponse.ProtoReflect.Descriptor instead.
func (*AddPersonalPromoCodeResponse) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{1}
}

func (x *AddPersonalPromoCodeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GetPromoCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPromoCodeRequest) Reset() {
	*x = GetPromoCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPromoCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoCodeRequest) ProtoMessage() {}

func (x *GetPromoCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoCodeRequest.ProtoReflect.Descriptor instead.
func (*GetPromoCodeRequest) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{2}
}

func (x *GetPromoCodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPromoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetPromoCodeResponse) Reset() {
	*x = GetPromoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPromoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPromoCodeResponse) ProtoMessage() {}

func (x *GetPromoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPromoCodeResponse.ProtoReflect.Descriptor instead.
func (*GetPromoCodeResponse) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{3}
}

func (x *GetPromoCodeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type GetAllPromoCodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllPromoCodesRequest) Reset() {
	*x = GetAllPromoCodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPromoCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPromoCodesRequest) ProtoMessage() {}

func (x *GetAllPromoCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPromoCodesRequest.ProtoReflect.Descriptor instead.
func (*GetAllPromoCodesRequest) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{4}
}

type GetAllPromoCodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetAllPromoCodesResponse) Reset() {
	*x = GetAllPromoCodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPromoCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPromoCodesResponse) ProtoMessage() {}

func (x *GetAllPromoCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPromoCodesResponse.ProtoReflect.Descriptor instead.
func (*GetAllPromoCodesResponse) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllPromoCodesResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ChangeNamePromoCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NewName string `protobuf:"bytes,2,opt,name=newName,proto3" json:"newName,omitempty"`
}

func (x *ChangeNamePromoCodeRequest) Reset() {
	*x = ChangeNamePromoCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeNamePromoCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeNamePromoCodeRequest) ProtoMessage() {}

func (x *ChangeNamePromoCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeNamePromoCodeRequest.ProtoReflect.Descriptor instead.
func (*ChangeNamePromoCodeRequest) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeNamePromoCodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChangeNamePromoCodeRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type ChangeNamePromoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ChangeNamePromoCodeResponse) Reset() {
	*x = ChangeNamePromoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeNamePromoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeNamePromoCodeResponse) ProtoMessage() {}

func (x *ChangeNamePromoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeNamePromoCodeResponse.ProtoReflect.Descriptor instead.
func (*ChangeNamePromoCodeResponse) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeNamePromoCodeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ChangeTypeDiscountPromoCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeDiscount int32  `protobuf:"varint,1,opt,name=typeDiscount,proto3" json:"typeDiscount,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChangeTypeDiscountPromoCodeRequest) Reset() {
	*x = ChangeTypeDiscountPromoCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeTypeDiscountPromoCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTypeDiscountPromoCodeRequest) ProtoMessage() {}

func (x *ChangeTypeDiscountPromoCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTypeDiscountPromoCodeRequest.ProtoReflect.Descriptor instead.
func (*ChangeTypeDiscountPromoCodeRequest) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeTypeDiscountPromoCodeRequest) GetTypeDiscount() int32 {
	if x != nil {
		return x.TypeDiscount
	}
	return 0
}

func (x *ChangeTypeDiscountPromoCodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangeTypeDiscountPromoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ChangeTypeDiscountPromoCodeResponse) Reset() {
	*x = ChangeTypeDiscountPromoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeTypeDiscountPromoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTypeDiscountPromoCodeResponse) ProtoMessage() {}

func (x *ChangeTypeDiscountPromoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTypeDiscountPromoCodeResponse.ProtoReflect.Descriptor instead.
func (*ChangeTypeDiscountPromoCodeResponse) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeTypeDiscountPromoCodeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ChangeValueDiscountPromoCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValueDiscount int32  `protobuf:"varint,1,opt,name=valueDiscount,proto3" json:"valueDiscount,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChangeValueDiscountPromoCodeRequest) Reset() {
	*x = ChangeValueDiscountPromoCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeValueDiscountPromoCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeValueDiscountPromoCodeRequest) ProtoMessage() {}

func (x *ChangeValueDiscountPromoCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeValueDiscountPromoCodeRequest.ProtoReflect.Descriptor instead.
func (*ChangeValueDiscountPromoCodeRequest) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeValueDiscountPromoCodeRequest) GetValueDiscount() int32 {
	if x != nil {
		return x.ValueDiscount
	}
	return 0
}

func (x *ChangeValueDiscountPromoCodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangeValueDiscountPromoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ChangeValueDiscountPromoCodeResponse) Reset() {
	*x = ChangeValueDiscountPromoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeValueDiscountPromoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeValueDiscountPromoCodeResponse) ProtoMessage() {}

func (x *ChangeValueDiscountPromoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeValueDiscountPromoCodeResponse.ProtoReflect.Descriptor instead.
func (*ChangeValueDiscountPromoCodeResponse) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeValueDiscountPromoCodeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ChangeDateStartActivePromoCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateStartActive string `protobuf:"bytes,1,opt,name=dateStartActive,proto3" json:"dateStartActive,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChangeDateStartActivePromoCodeRequest) Reset() {
	*x = ChangeDateStartActivePromoCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeDateStartActivePromoCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDateStartActivePromoCodeRequest) ProtoMessage() {}

func (x *ChangeDateStartActivePromoCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDateStartActivePromoCodeRequest.ProtoReflect.Descriptor instead.
func (*ChangeDateStartActivePromoCodeRequest) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeDateStartActivePromoCodeRequest) GetDateStartActive() string {
	if x != nil {
		return x.DateStartActive
	}
	return ""
}

func (x *ChangeDateStartActivePromoCodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangeDateStartActivePromoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ChangeDateStartActivePromoCodeResponse) Reset() {
	*x = ChangeDateStartActivePromoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeDateStartActivePromoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDateStartActivePromoCodeResponse) ProtoMessage() {}

func (x *ChangeDateStartActivePromoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDateStartActivePromoCodeResponse.ProtoReflect.Descriptor instead.
func (*ChangeDateStartActivePromoCodeResponse) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeDateStartActivePromoCodeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ChangeDateFinishActivePromoCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateFinishActive string `protobuf:"bytes,1,opt,name=dateFinishActive,proto3" json:"dateFinishActive,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChangeDateFinishActivePromoCodeRequest) Reset() {
	*x = ChangeDateFinishActivePromoCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeDateFinishActivePromoCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDateFinishActivePromoCodeRequest) ProtoMessage() {}

func (x *ChangeDateFinishActivePromoCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDateFinishActivePromoCodeRequest.ProtoReflect.Descriptor instead.
func (*ChangeDateFinishActivePromoCodeRequest) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{14}
}

func (x *ChangeDateFinishActivePromoCodeRequest) GetDateFinishActive() string {
	if x != nil {
		return x.DateFinishActive
	}
	return ""
}

func (x *ChangeDateFinishActivePromoCodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangeDateFinishActivePromoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ChangeDateFinishActivePromoCodeResponse) Reset() {
	*x = ChangeDateFinishActivePromoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeDateFinishActivePromoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDateFinishActivePromoCodeResponse) ProtoMessage() {}

func (x *ChangeDateFinishActivePromoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDateFinishActivePromoCodeResponse.ProtoReflect.Descriptor instead.
func (*ChangeDateFinishActivePromoCodeResponse) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{15}
}

func (x *ChangeDateFinishActivePromoCodeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ChangeMaxCountUsesPromoCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxCountUses int32  `protobuf:"varint,1,opt,name=maxCountUses,proto3" json:"maxCountUses,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ChangeMaxCountUsesPromoCodeRequest) Reset() {
	*x = ChangeMaxCountUsesPromoCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeMaxCountUsesPromoCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMaxCountUsesPromoCodeRequest) ProtoMessage() {}

func (x *ChangeMaxCountUsesPromoCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMaxCountUsesPromoCodeRequest.ProtoReflect.Descriptor instead.
func (*ChangeMaxCountUsesPromoCodeRequest) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{16}
}

func (x *ChangeMaxCountUsesPromoCodeRequest) GetMaxCountUses() int32 {
	if x != nil {
		return x.MaxCountUses
	}
	return 0
}

func (x *ChangeMaxCountUsesPromoCodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChangeMaxCountUsesPromoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ChangeMaxCountUsesPromoCodeResponse) Reset() {
	*x = ChangeMaxCountUsesPromoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeMaxCountUsesPromoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMaxCountUsesPromoCodeResponse) ProtoMessage() {}

func (x *ChangeMaxCountUsesPromoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMaxCountUsesPromoCodeResponse.ProtoReflect.Descriptor instead.
func (*ChangeMaxCountUsesPromoCodeResponse) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{17}
}

func (x *ChangeMaxCountUsesPromoCodeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DeletePromoCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeletePromoCodeRequest) Reset() {
	*x = DeletePromoCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePromoCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromoCodeRequest) ProtoMessage() {}

func (x *DeletePromoCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromoCodeRequest.ProtoReflect.Descriptor instead.
func (*DeletePromoCodeRequest) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{18}
}

func (x *DeletePromoCodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeletePromoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DeletePromoCodeResponse) Reset() {
	*x = DeletePromoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePromoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePromoCodeResponse) ProtoMessage() {}

func (x *DeletePromoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePromoCodeResponse.ProtoReflect.Descriptor instead.
func (*DeletePromoCodeResponse) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{19}
}

func (x *DeletePromoCodeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type AddNewPromoCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeDiscount     int32  `protobuf:"varint,2,opt,name=typeDiscount,proto3" json:"typeDiscount,omitempty"`
	ValueDiscount    int32  `protobuf:"varint,3,opt,name=valueDiscount,proto3" json:"valueDiscount,omitempty"`
	DateStartActive  string `protobuf:"bytes,4,opt,name=dateStartActive,proto3" json:"dateStartActive,omitempty"`
	DateFinishActive string `protobuf:"bytes,5,opt,name=dateFinishActive,proto3" json:"dateFinishActive,omitempty"`
	MaxCountUses     int32  `protobuf:"varint,6,opt,name=maxCountUses,proto3" json:"maxCountUses,omitempty"`
}

func (x *AddNewPromoCodeRequest) Reset() {
	*x = AddNewPromoCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewPromoCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewPromoCodeRequest) ProtoMessage() {}

func (x *AddNewPromoCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewPromoCodeRequest.ProtoReflect.Descriptor instead.
func (*AddNewPromoCodeRequest) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{20}
}

func (x *AddNewPromoCodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddNewPromoCodeRequest) GetTypeDiscount() int32 {
	if x != nil {
		return x.TypeDiscount
	}
	return 0
}

func (x *AddNewPromoCodeRequest) GetValueDiscount() int32 {
	if x != nil {
		return x.ValueDiscount
	}
	return 0
}

func (x *AddNewPromoCodeRequest) GetDateStartActive() string {
	if x != nil {
		return x.DateStartActive
	}
	return ""
}

func (x *AddNewPromoCodeRequest) GetDateFinishActive() string {
	if x != nil {
		return x.DateFinishActive
	}
	return ""
}

func (x *AddNewPromoCodeRequest) GetMaxCountUses() int32 {
	if x != nil {
		return x.MaxCountUses
	}
	return 0
}

type AddNewPromoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddNewPromoCodeResponse) Reset() {
	*x = AddNewPromoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceLoyalty_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewPromoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewPromoCodeResponse) ProtoMessage() {}

func (x *AddNewPromoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceLoyalty_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewPromoCodeResponse.ProtoReflect.Descriptor instead.
func (*AddNewPromoCodeResponse) Descriptor() ([]byte, []int) {
	return file_ServiceLoyalty_proto_rawDescGZIP(), []int{21}
}

func (x *AddNewPromoCodeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_ServiceLoyalty_proto protoreflect.FileDescriptor

var file_ServiceLoyalty_proto_rawDesc = []byte{
	0x0a, 0x14, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x79, 0x0a, 0x1b, 0x41, 0x64, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x69, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x64,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x64, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x6d,
	0x6f, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x61, 0x6d,
	0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x36, 0x0a, 0x1c, 0x41, 0x64,
	0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x29, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x19, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4a, 0x0a, 0x1a,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x1b, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x5c, 0x0a, 0x22, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x79, 0x70, 0x65, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x79, 0x70,
	0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a,
	0x23, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x5f, 0x0a, 0x23,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a,
	0x24, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x65, 0x0a,
	0x25, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x26, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61,
	0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x72, 0x6f,
	0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x68, 0x0a, 0x26, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2a, 0x0a, 0x10, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x41, 0x0a, 0x27, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x5c, 0x0a, 0x22, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x61, 0x78,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x78,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x3d, 0x0a, 0x23, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x61, 0x78, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x2c, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x31,
	0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0xf0, 0x01, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x6d,
	0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x74, 0x79, 0x70, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x79, 0x70, 0x65, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x55, 0x73, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xa5, 0x09, 0x0a, 0x0e, 0x4c, 0x6f, 0x79, 0x61,
	0x6c, 0x74, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x41, 0x64,
	0x64, 0x4e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x50,
	0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x54, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x13, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x78, 0x0a, 0x1b, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x7b, 0x0a, 0x1c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x2c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x81, 0x01, 0x0a, 0x1e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x2e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x84, 0x01, 0x0a, 0x1f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x78, 0x0a, 0x1b, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x73,
	0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x61, 0x78, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x55, 0x73, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x61, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x55,
	0x73, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x57, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x6d, 0x6f,
	0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x14, 0x41, 0x64,
	0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x24, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x72,
	0x6f, 0x6d, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x14, 0x5a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x6c, 0x6f, 0x79, 0x61, 0x6c,
	0x74, 0x79, 0x3b, 0x73, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ServiceLoyalty_proto_rawDescOnce sync.Once
	file_ServiceLoyalty_proto_rawDescData = file_ServiceLoyalty_proto_rawDesc
)

func file_ServiceLoyalty_proto_rawDescGZIP() []byte {
	file_ServiceLoyalty_proto_rawDescOnce.Do(func() {
		file_ServiceLoyalty_proto_rawDescData = protoimpl.X.CompressGZIP(file_ServiceLoyalty_proto_rawDescData)
	})
	return file_ServiceLoyalty_proto_rawDescData
}

var file_ServiceLoyalty_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_ServiceLoyalty_proto_goTypes = []interface{}{
	(*AddPersonalPromoCodeRequest)(nil),             // 0: service.AddPersonalPromoCodeRequest
	(*AddPersonalPromoCodeResponse)(nil),            // 1: service.AddPersonalPromoCodeResponse
	(*GetPromoCodeRequest)(nil),                     // 2: service.GetPromoCodeRequest
	(*GetPromoCodeResponse)(nil),                    // 3: service.GetPromoCodeResponse
	(*GetAllPromoCodesRequest)(nil),                 // 4: service.GetAllPromoCodesRequest
	(*GetAllPromoCodesResponse)(nil),                // 5: service.GetAllPromoCodesResponse
	(*ChangeNamePromoCodeRequest)(nil),              // 6: service.ChangeNamePromoCodeRequest
	(*ChangeNamePromoCodeResponse)(nil),             // 7: service.ChangeNamePromoCodeResponse
	(*ChangeTypeDiscountPromoCodeRequest)(nil),      // 8: service.ChangeTypeDiscountPromoCodeRequest
	(*ChangeTypeDiscountPromoCodeResponse)(nil),     // 9: service.ChangeTypeDiscountPromoCodeResponse
	(*ChangeValueDiscountPromoCodeRequest)(nil),     // 10: service.ChangeValueDiscountPromoCodeRequest
	(*ChangeValueDiscountPromoCodeResponse)(nil),    // 11: service.ChangeValueDiscountPromoCodeResponse
	(*ChangeDateStartActivePromoCodeRequest)(nil),   // 12: service.ChangeDateStartActivePromoCodeRequest
	(*ChangeDateStartActivePromoCodeResponse)(nil),  // 13: service.ChangeDateStartActivePromoCodeResponse
	(*ChangeDateFinishActivePromoCodeRequest)(nil),  // 14: service.ChangeDateFinishActivePromoCodeRequest
	(*ChangeDateFinishActivePromoCodeResponse)(nil), // 15: service.ChangeDateFinishActivePromoCodeResponse
	(*ChangeMaxCountUsesPromoCodeRequest)(nil),      // 16: service.ChangeMaxCountUsesPromoCodeRequest
	(*ChangeMaxCountUsesPromoCodeResponse)(nil),     // 17: service.ChangeMaxCountUsesPromoCodeResponse
	(*DeletePromoCodeRequest)(nil),                  // 18: service.DeletePromoCodeRequest
	(*DeletePromoCodeResponse)(nil),                 // 19: service.DeletePromoCodeResponse
	(*AddNewPromoCodeRequest)(nil),                  // 20: service.AddNewPromoCodeRequest
	(*AddNewPromoCodeResponse)(nil),                 // 21: service.AddNewPromoCodeResponse
}
var file_ServiceLoyalty_proto_depIdxs = []int32{
	20, // 0: service.LoyaltyService.AddNewPromoCode:input_type -> service.AddNewPromoCodeRequest
	18, // 1: service.LoyaltyService.DeletePromoCode:input_type -> service.DeletePromoCodeRequest
	6,  // 2: service.LoyaltyService.ChangeNamePromoCode:input_type -> service.ChangeNamePromoCodeRequest
	8,  // 3: service.LoyaltyService.ChangeTypeDiscountPromoCode:input_type -> service.ChangeTypeDiscountPromoCodeRequest
	10, // 4: service.LoyaltyService.ChangeValueDiscountPromoCode:input_type -> service.ChangeValueDiscountPromoCodeRequest
	12, // 5: service.LoyaltyService.ChangeDateStartActivePromoCode:input_type -> service.ChangeDateStartActivePromoCodeRequest
	14, // 6: service.LoyaltyService.ChangeDateFinishActivePromoCode:input_type -> service.ChangeDateFinishActivePromoCodeRequest
	16, // 7: service.LoyaltyService.ChangeMaxCountUsesPromoCode:input_type -> service.ChangeMaxCountUsesPromoCodeRequest
	2,  // 8: service.LoyaltyService.GetPromoCode:input_type -> service.GetPromoCodeRequest
	4,  // 9: service.LoyaltyService.GetAllPromoCodes:input_type -> service.GetAllPromoCodesRequest
	0,  // 10: service.LoyaltyService.AddPersonalPromoCode:input_type -> service.AddPersonalPromoCodeRequest
	21, // 11: service.LoyaltyService.AddNewPromoCode:output_type -> service.AddNewPromoCodeResponse
	19, // 12: service.LoyaltyService.DeletePromoCode:output_type -> service.DeletePromoCodeResponse
	7,  // 13: service.LoyaltyService.ChangeNamePromoCode:output_type -> service.ChangeNamePromoCodeResponse
	9,  // 14: service.LoyaltyService.ChangeTypeDiscountPromoCode:output_type -> service.ChangeTypeDiscountPromoCodeResponse
	11, // 15: service.LoyaltyService.ChangeValueDiscountPromoCode:output_type -> service.ChangeValueDiscountPromoCodeResponse
	13, // 16: service.LoyaltyService.ChangeDateStartActivePromoCode:output_type -> service.ChangeDateStartActivePromoCodeResponse
	15, // 17: service.LoyaltyService.ChangeDateFinishActivePromoCode:output_type -> service.ChangeDateFinishActivePromoCodeResponse
	17, // 18: service.LoyaltyService.ChangeMaxCountUsesPromoCode:output_type -> service.ChangeMaxCountUsesPromoCodeResponse
	3,  // 19: service.LoyaltyService.GetPromoCode:output_type -> service.GetPromoCodeResponse
	5,  // 20: service.LoyaltyService.GetAllPromoCodes:output_type -> service.GetAllPromoCodesResponse
	1,  // 21: service.LoyaltyService.AddPersonalPromoCode:output_type -> service.AddPersonalPromoCodeResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_ServiceLoyalty_proto_init() }
func file_ServiceLoyalty_proto_init() {
	if File_ServiceLoyalty_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ServiceLoyalty_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPersonalPromoCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPersonalPromoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPromoCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPromoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllPromoCodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllPromoCodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeNamePromoCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeNamePromoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeTypeDiscountPromoCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeTypeDiscountPromoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeValueDiscountPromoCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeValueDiscountPromoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeDateStartActivePromoCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeDateStartActivePromoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeDateFinishActivePromoCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeDateFinishActivePromoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeMaxCountUsesPromoCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeMaxCountUsesPromoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePromoCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePromoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewPromoCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceLoyalty_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewPromoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ServiceLoyalty_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ServiceLoyalty_proto_goTypes,
		DependencyIndexes: file_ServiceLoyalty_proto_depIdxs,
		MessageInfos:      file_ServiceLoyalty_proto_msgTypes,
	}.Build()
	File_ServiceLoyalty_proto = out.File
	file_ServiceLoyalty_proto_rawDesc = nil
	file_ServiceLoyalty_proto_goTypes = nil
	file_ServiceLoyalty_proto_depIdxs = nil
}
